version: '3.4'

services:
  frontend:
    build:
      context: ./cinemasphere-front
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SUPABASE_URL=https://apddrjqwvnrtjmmmlgmk.supabase.co
      - REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZGRyanF3dm5ydGptbW1sZ21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUyMDk4MDMsImV4cCI6MjAzMDc4NTgwM30.s4vQy93YuDfd5MzRhB0i_k8MgZRHif5Ji20mZ7GsqQQ
    depends_on:
      - backend

  backend:
    build:
      context: ./cinemasphere-back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - REACT_APP_SUPABASE_URL=https://apddrjqwvnrtjmmmlgmk.supabase.co
      - REACT_APP_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZGRyanF3dm5ydGptbW1sZ21rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTUyMDk4MDMsImV4cCI6MjAzMDc4NTgwM30.s4vQy93YuDfd5MzRhB0i_k8MgZRHif5Ji20mZ7GsqQQ